# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
  - repo: local
    # We do not use pre-commit/mirrors-mypy,
    # as it comes with opinionated defaults
    # (like --ignore-missing-imports)
    # and is difficult to configure to run
    # with the dependencies correctly installed.
    hooks:
      - id: mypy
        name: mypy
        entry: "./run-mypy.sh"
        language: python
        language_version: python3.10
        # additional_dependencies: ["mypy==0.961"]
        types: [python]
        require_serial: true
        verbose: true
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
#  - repo: https://github.com/PyCQA/bandit
#    rev: 1.7.4
#    hooks:
#      - id: bandit
#        name: bandit
#        args: ["-x", "*/tests/*", "-c", "pyproject.toml", "-r", "."] # Also in pyproject.toml
#        additional_dependencies: [ "bandit[toml]" ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        exclude: ^tests/
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
